/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/modules": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * List Modules
         * @description A page of catalogued modules, optionally filtered by tracker format.
         */
        readonly get: operations["list_modules_modules_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/modules/{module_hash}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Module
         * @description One module's own fields plus every sample occurrence it declares.
         *
         *     Raises:
         *         HTTPException: 404 when no module is catalogued under this hash.
         */
        readonly get: operations["get_module_modules__module_hash__get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/samples": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * List Samples
         * @description A page of catalogued samples, ranked by how many module occurrences reference each one.
         *
         *     Ranks by sample identity: one row per exact content hash. Ranking by equivalence class --
         *     grouping near-duplicate variants into one row -- is a planned future mode, not available yet.
         */
        readonly get: operations["list_samples_samples_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/samples/{sample_hash}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Sample
         * @description One sample's own fields plus every module occurrence that references it.
         *
         *     Raises:
         *         HTTPException: 404 when no sample is catalogued under this hash.
         */
        readonly get: operations["get_sample_samples__sample_hash__get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/samples/{sample_hash}/audio": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Sample Audio
         * @description The sample's own canonical audio, as stored in the content-addressable store.
         *
         *     Raises:
         *         HTTPException: 404 when no sample is catalogued under this hash.
         */
        readonly get: operations["get_sample_audio_samples__sample_hash__audio_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/samples/{sample_hash}/waveform": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Sample Waveform
         * @description A compact amplitude-envelope preview of the sample's own waveform.
         *
         *     Raises:
         *         HTTPException: 404 when no sample is catalogued under this hash.
         */
        readonly get: operations["get_sample_waveform_samples__sample_hash__waveform_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/samples/{sample_hash}/relations": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Sample Relations
         * @description Every equivalence-class link this sample participates in, on either side of the pair.
         *
         *     Raises:
         *         HTTPException: 404 when no sample is catalogued under this hash.
         */
        readonly get: operations["get_sample_relations_samples__sample_hash__relations_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/stats": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Stats
         * @description A snapshot of the catalog's overall size and composition.
         */
        readonly get: operations["get_stats_stats_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/cloud": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Cloud
         * @description Every sample's position in the library's 2D embedding space, as of the latest embedding run.
         */
        readonly get: operations["get_cloud_cloud_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BitDepth
         * @description How many bits one stored frame of PCM occupies.
         * @enum {integer}
         */
        readonly BitDepth: 8 | 16;
        /**
         * ChannelLayout
         * @description How many interleaved channels one frame of a Sample's waveform carries.
         * @enum {integer}
         */
        readonly ChannelLayout: 1 | 2;
        /** HTTPValidationError */
        readonly HTTPValidationError: {
            /** Detail */
            readonly detail?: readonly components["schemas"]["ValidationError"][];
        };
        /**
         * ITSampleProperties
         * @description The occurrence fields Impulse Tracker stores beside the shared ones.
         *
         *     ``global_volume`` is IT's own per-sample gain multiplier; FastTracker 2 has no equivalent
         *     slot, so it is not part of the shared base. ``filename`` and ``vibrato`` are this format's own
         *     DOS filename and sample-level auto-vibrato.
         */
        readonly ITSampleProperties: {
            /** Sample Hash */
            readonly sample_hash: string;
            readonly occurrence: components["schemas"]["SampleOccurrence"];
            /** Name */
            readonly name: string;
            /** Rate */
            readonly rate: number;
            /** Volume */
            readonly volume: number;
            /** Panning */
            readonly panning?: number | null;
            readonly loop?: components["schemas"]["Loop"] | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly tracker: "it";
            /** Global Volume */
            readonly global_volume: number;
            readonly sustain_loop?: components["schemas"]["Loop"] | null;
            /** Filename */
            readonly filename?: string | null;
            readonly vibrato?: components["schemas"]["Vibrato"] | null;
        };
        /**
         * LibraryStats
         * @description A snapshot of the catalog's overall size and composition.
         */
        readonly LibraryStats: {
            /** Module Count */
            readonly module_count: number;
            /** Sample Count */
            readonly sample_count: number;
            /** Sample Properties Count */
            readonly sample_properties_count: number;
            /** Modules By Tracker */
            readonly modules_by_tracker: readonly components["schemas"]["TrackerModuleCount"][];
            /** Relations By Type */
            readonly relations_by_type: readonly components["schemas"]["RelationTypeCount"][];
            /** Total Stored Bytes */
            readonly total_stored_bytes: number;
        };
        /**
         * Loop
         * @description A half-open frame range ``[begin, end)`` playback repeats once it reaches ``end``.
         */
        readonly Loop: {
            /** Begin */
            readonly begin: number;
            /** End */
            readonly end: number;
            /** @default forward */
            readonly mode: components["schemas"]["LoopMode"];
        };
        /**
         * LoopMode
         * @description How playback repeats a looped region.
         * @enum {string}
         */
        readonly LoopMode: "forward" | "ping_pong";
        /**
         * Module
         * @description A tracker module file's identity and the shape of the song it stores.
         *
         *     ``hash`` content-addresses the exact file bytes; ``id`` is the library's own sequential handle
         *     for it, the pair mirroring how modsamplemaster.org identifies a module by both a hash and an
         *     id. ``filename`` is the module's own filename at ingestion time with no directory component --
         *     the local path it was ingested from is never recorded, only the name the file itself carried.
         */
        readonly Module: {
            /** Hash */
            readonly hash: string;
            /** Id */
            readonly id: number;
            /** Filename */
            readonly filename: string;
            readonly tracker: components["schemas"]["TrackerFormat"];
            /** Title */
            readonly title: string;
            /** Channel Count */
            readonly channel_count: number;
            /** Pattern Count */
            readonly pattern_count: number;
            /** Instrument Count */
            readonly instrument_count: number;
            /** Sample Count */
            readonly sample_count: number;
            /** File Size */
            readonly file_size: number;
            /**
             * Ingested At
             * Format: date-time
             */
            readonly ingested_at: string;
        };
        /**
         * ModuleDetail
         * @description A module together with every sample occurrence it declares.
         */
        readonly ModuleDetail: {
            /** Hash */
            readonly hash: string;
            /** Id */
            readonly id: number;
            /** Filename */
            readonly filename: string;
            readonly tracker: components["schemas"]["TrackerFormat"];
            /** Title */
            readonly title: string;
            /** Channel Count */
            readonly channel_count: number;
            /** Pattern Count */
            readonly pattern_count: number;
            /** Instrument Count */
            readonly instrument_count: number;
            /** Sample Count */
            readonly sample_count: number;
            /** File Size */
            readonly file_size: number;
            /**
             * Ingested At
             * Format: date-time
             */
            readonly ingested_at: string;
            /** Occurrences */
            readonly occurrences: readonly components["schemas"]["ModuleOccurrenceDetail"][];
        };
        /**
         * ModuleOccurrenceDetail
         * @description One sample occurrence a module declares, together with the Sample content it points at.
         */
        readonly ModuleOccurrenceDetail: {
            /** Properties */
            readonly properties: components["schemas"]["XMSampleProperties"] | components["schemas"]["ITSampleProperties"];
            readonly sample: components["schemas"]["ModuleOccurrenceSample"];
        };
        /**
         * ModuleOccurrenceSample
         * @description The resolved Sample content one module occurrence points at, alongside its cached thumbnail.
         *
         *     ``size_bytes`` re-exposes ``Sample.stored_bytes`` under its own name, the same rename
         *     ``SampleSummary`` already uses: a Pydantic field cannot share a name with an inherited plain
         *     property without the property silently winning on attribute access.
         */
        readonly ModuleOccurrenceSample: {
            /** Hash */
            readonly hash: string;
            readonly depth: components["schemas"]["BitDepth"];
            readonly channels: components["schemas"]["ChannelLayout"];
            /** Frames */
            readonly frames: number;
            /** Size Bytes */
            readonly size_bytes: number;
            /** Thumbnail */
            readonly thumbnail: readonly components["schemas"]["WaveformPeak"][] | null;
        };
        /** Page[Module] */
        readonly Page_Module_: {
            /** Items */
            readonly items: readonly components["schemas"]["Module"][];
            /** Total */
            readonly total: number;
            /** Limit */
            readonly limit: number;
            /** Offset */
            readonly offset: number;
        };
        /** Page[SampleSummary] */
        readonly Page_SampleSummary_: {
            /** Items */
            readonly items: readonly components["schemas"]["SampleSummary"][];
            /** Total */
            readonly total: number;
            /** Limit */
            readonly limit: number;
            /** Offset */
            readonly offset: number;
        };
        /**
         * RelationReview
         * @description A curator's verdict on an automatically proposed SampleRelation, once one has been made.
         */
        readonly RelationReview: {
            /** Confirmed */
            readonly confirmed: boolean;
            /**
             * Reviewed At
             * Format: date-time
             */
            readonly reviewed_at: string;
            /** Reviewed By */
            readonly reviewed_by: string;
        };
        /**
         * RelationType
         * @description The kind of near-duplicate link two distinct Samples can be proposed to share.
         * @enum {string}
         */
        readonly RelationType: "bit_depth_variant" | "resampled_variant";
        /**
         * RelationTypeCount
         * @description How many detected equivalence-class links belong to one relation type.
         */
        readonly RelationTypeCount: {
            readonly relation_type: components["schemas"]["RelationType"];
            /** Relation Count */
            readonly relation_count: number;
        };
        /**
         * SampleCloudCoordinate
         * @description Where one Sample sits in the library's 2D embedding space, as of one embedding run.
         *
         *     A full embedding run recomputes every sample's position at once -- UMAP has no natural
         *     per-point incremental update -- so a later run's coordinate for a given hash entirely replaces
         *     an earlier one, rather than the two ever coexisting.
         */
        readonly SampleCloudCoordinate: {
            /** Sample Hash */
            readonly sample_hash: string;
            /** X */
            readonly x: number;
            /** Y */
            readonly y: number;
            /**
             * Computed At
             * Format: date-time
             */
            readonly computed_at: string;
        };
        /**
         * SampleDetail
         * @description A sample together with every module occurrence that references it.
         */
        readonly SampleDetail: {
            /** Hash */
            readonly hash: string;
            readonly depth: components["schemas"]["BitDepth"];
            readonly channels: components["schemas"]["ChannelLayout"];
            /** Frames */
            readonly frames: number;
            /** Occurrences */
            readonly occurrences: readonly components["schemas"]["SampleOccurrenceDetail"][];
            /** Size Bytes */
            readonly size_bytes: number;
            /** Display Name */
            readonly display_name: string;
            /** Duration Seconds */
            readonly duration_seconds: number;
        };
        /**
         * SampleOccurrence
         * @description Which one slot, in which one module, a SampleProperties row describes.
         *
         *     An instrument owns an ordered tuple of samples; ``sample_slot`` is a sample's position in
         *     that tuple -- the only handle XM or IT gives one occurrence, since neither assigns samples
         *     their own identifier independent of the instrument that owns them.
         */
        readonly SampleOccurrence: {
            /** Module Hash */
            readonly module_hash: string;
            /** Instrument Index */
            readonly instrument_index: number;
            /** Sample Slot */
            readonly sample_slot: number;
        };
        /**
         * SampleOccurrenceDetail
         * @description One module occurrence of a sample, together with the module it belongs to.
         */
        readonly SampleOccurrenceDetail: {
            /** Properties */
            readonly properties: components["schemas"]["XMSampleProperties"] | components["schemas"]["ITSampleProperties"];
            readonly module: components["schemas"]["SampleOccurrenceModule"];
        };
        /**
         * SampleOccurrenceModule
         * @description The module context a sample occurrence belongs to, resolved for display alongside it.
         */
        readonly SampleOccurrenceModule: {
            /** Hash */
            readonly hash: string;
            /** Filename */
            readonly filename: string;
            /** Title */
            readonly title: string;
            readonly tracker: components["schemas"]["TrackerFormat"];
        };
        /**
         * SampleRelation
         * @description One automatically detected, optionally curator-reviewed link between two Samples.
         *
         *     ``subject_hash`` is always the lexicographically smaller of the two hashes, so the same pair,
         *     found by two different detection methods or in either order, always lands on the same identity
         *     for review purposes; ``method`` still lets independent detectors each record their own row for
         *     the same pair, so agreement between methods is itself visible corroborating evidence rather
         *     than being collapsed away.
         */
        readonly SampleRelation: {
            /** Id */
            readonly id: number;
            /** Subject Hash */
            readonly subject_hash: string;
            /** Reference Hash */
            readonly reference_hash: string;
            readonly relation_type: components["schemas"]["RelationType"];
            /** Method */
            readonly method: string;
            /** Confidence */
            readonly confidence: number;
            /** Evidence */
            readonly evidence: {
                readonly [key: string]: number;
            };
            /**
             * Detected At
             * Format: date-time
             */
            readonly detected_at: string;
            readonly review?: components["schemas"]["RelationReview"] | null;
        };
        /**
         * SampleSummary
         * @description One row of a paginated, occurrence-ranked samples listing.
         *
         *     Ranks samples by identity -- one row per exact content hash -- rather than by equivalence
         *     class; grouping near-duplicate variants into one row is a distinct future ranking mode, not a
         *     hidden variant of this one. `display_name` resolves the sample's, possibly conflicting,
         *     occurrence names via `samplecore.naming.choose_dominant_name`. ``size_bytes`` re-exposes
         *     ``Sample.stored_bytes`` under its own name: a Pydantic field cannot share a name with an
         *     inherited plain property without the property silently winning on attribute access.
         *     ``thumbnail`` is ``None`` for a sample whose cached waveform preview has not been computed yet.
         */
        readonly SampleSummary: {
            /** Hash */
            readonly hash: string;
            readonly depth: components["schemas"]["BitDepth"];
            readonly channels: components["schemas"]["ChannelLayout"];
            /** Frames */
            readonly frames: number;
            /** Occurrence Count */
            readonly occurrence_count: number;
            /** Display Name */
            readonly display_name: string;
            /** Size Bytes */
            readonly size_bytes: number;
            /** Thumbnail */
            readonly thumbnail: readonly components["schemas"]["WaveformPeak"][] | null;
        };
        /**
         * TrackerFormat
         * @description Which tracker format a module or a sample occurrence belongs to.
         * @enum {string}
         */
        readonly TrackerFormat: "xm" | "it";
        /**
         * TrackerModuleCount
         * @description How many catalogued modules belong to one tracker format.
         */
        readonly TrackerModuleCount: {
            readonly tracker: components["schemas"]["TrackerFormat"];
            /** Module Count */
            readonly module_count: number;
        };
        /**
         * Tuning
         * @description How far a stored sample is transposed from the key that triggers it.
         *
         *     FastTracker 2 stores no playback rate. A sample sounds at the pitch of the key it is played on,
         *     shifted by ``relative_note`` whole semitones and trimmed by ``finetune`` in units of one
         *     :data:`~trackmod.xm.spec.tuning.FINETUNE_UNITS`-th of a semitone, so a rate is expressed as a
         *     transposition rather than stored outright.
         */
        readonly Tuning: {
            /** Relative Note */
            readonly relative_note: number;
            /** Finetune */
            readonly finetune: number;
        };
        /** ValidationError */
        readonly ValidationError: {
            /** Location */
            readonly loc: readonly (string | number)[];
            /** Message */
            readonly msg: string;
            /** Error Type */
            readonly type: string;
            /** Input */
            readonly input?: unknown;
            /** Context */
            readonly ctx?: Record<string, never>;
        };
        /**
         * Vibrato
         * @description The auto-vibrato an Impulse Tracker sample header carries in its own right.
         *
         *     Newer instrument-format modules commonly leave this at its silent default and drive vibrato
         *     from the owning instrument instead, but the sample header field exists regardless of which a
         *     given module actually relies on, so it is captured here rather than assumed unused.
         */
        readonly Vibrato: {
            /** Speed */
            readonly speed: number;
            /** Depth */
            readonly depth: number;
            /** Rate */
            readonly rate: number;
            /** Waveform */
            readonly waveform: number;
        };
        /**
         * WaveformPeak
         * @description One bucket's amplitude envelope in a compact waveform preview.
         */
        readonly WaveformPeak: {
            /** Minimum */
            readonly minimum: number;
            /** Maximum */
            readonly maximum: number;
        };
        /**
         * XMSampleProperties
         * @description The occurrence fields FastTracker 2 stores beside the shared ones.
         *
         *     FastTracker 2 keeps no separate per-sample gain, no sustain loop, and no auto-vibrato on the
         *     sample itself, so ``tuning`` is the only field this format adds: the raw transposition its own
         *     header stores, which ``rate`` above was already derived from by TrackMod's XM reader.
         */
        readonly XMSampleProperties: {
            /** Sample Hash */
            readonly sample_hash: string;
            readonly occurrence: components["schemas"]["SampleOccurrence"];
            /** Name */
            readonly name: string;
            /** Rate */
            readonly rate: number;
            /** Volume */
            readonly volume: number;
            /** Panning */
            readonly panning?: number | null;
            readonly loop?: components["schemas"]["Loop"] | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly tracker: "xm";
            readonly tuning: components["schemas"]["Tuning"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly list_modules_modules_get: {
        readonly parameters: {
            readonly query?: {
                readonly limit?: number;
                readonly offset?: number;
                readonly tracker?: components["schemas"]["TrackerFormat"] | null;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Page_Module_"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_module_modules__module_hash__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly module_hash: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ModuleDetail"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly list_samples_samples_get: {
        readonly parameters: {
            readonly query?: {
                readonly limit?: number;
                readonly offset?: number;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Page_SampleSummary_"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_sample_samples__sample_hash__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly sample_hash: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SampleDetail"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_sample_audio_samples__sample_hash__audio_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly sample_hash: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": unknown;
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_sample_waveform_samples__sample_hash__waveform_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly sample_hash: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["WaveformPeak"][];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_sample_relations_samples__sample_hash__relations_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly sample_hash: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["SampleRelation"][];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_stats_stats_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["LibraryStats"];
                };
            };
        };
    };
    readonly get_cloud_cloud_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["SampleCloudCoordinate"][];
                };
            };
        };
    };
}
