/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/api/modules": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * List Modules
         * @description A page of cataloged modules, optionally filtered by tracker format.
         */
        readonly get: operations["list_modules_api_modules_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/modules/{module_hash}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Module
         * @description One module's own fields plus every sample occurrence it declares.
         *
         *     Raises:
         *         HTTPException: 404 when no module is cataloged under this hash.
         */
        readonly get: operations["get_module_api_modules__module_hash__get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/samples": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * List Samples
         * @description A page of the catalog's samples, narrowed and ordered by what a person has decided.
         *
         *     ``favorites_only`` and ``minimum_rating`` reach the whole catalog rather than one page, so a
         *     collection scattered across a hundred thousand samples still browses as a collection.
         *     ``group_by_equivalence`` collapses same-page rows sharing an equivalence class afterwards, which
         *     is why the total counts rows rather than groups.
         */
        readonly get: operations["list_samples_api_samples_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/samples/{sample_hash}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Sample
         * @description One sample's own fields plus every module occurrence that references it.
         *
         *     ``equivalence_member_count`` travels with the sample so a caller labeling it knows how many
         *     near-duplicates the same choice would reach.
         *
         *     Raises:
         *         HTTPException: 404 when no sample is cataloged under this hash.
         */
        readonly get: operations["get_sample_api_samples__sample_hash__get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/samples/{sample_hash}/audio": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Sample Audio
         * @description The sample's own canonical audio, as stored in the content-addressable store.
         *
         *     The object is content-addressed, so it is served with a cache lifetime of a year and read
         *     straight off the store by its hash, with no catalog round trip on the way to a sound: the
         *     hash's own shape is checked on the path, which is what keeps a request inside the store.
         *
         *     Raises:
         *         HTTPException: 404 when the store holds no object under this hash.
         */
        readonly get: operations["get_sample_audio_api_samples__sample_hash__audio_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/samples/{sample_hash}/preview": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Sample Preview
         * @description A sample as a hover shows it, read from what the catalog already holds and nothing decoded.
         *
         *     Four narrow lookups answer this, against the eight a detail makes: a tooltip appears on every
         *     point a cursor crosses, so it costs what a glance is worth.
         *
         *     Raises:
         *         HTTPException: 404 when no sample is cataloged under this hash.
         */
        readonly get: operations["get_sample_preview_api_samples__sample_hash__preview_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/samples/{sample_hash}/relations": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Sample Relations
         * @description Every equivalence-class link this sample participates in, on either side of the pair.
         *
         *     Raises:
         *         HTTPException: 404 when no sample is cataloged under this hash.
         */
        readonly get: operations["get_sample_relations_api_samples__sample_hash__relations_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/samples/{sample_hash}/distance/{other_hash}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Sample Distance
         * @description The Euclidean distance between two samples' persisted, standardized spectral feature vectors.
         *
         *     Raises:
         *         HTTPException: 404 when either sample has no persisted spectral feature vector yet -- not
         *             yet embedded, or embedded before this metric existed.
         */
        readonly get: operations["get_sample_distance_api_samples__sample_hash__distance__other_hash__get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/samples/{sample_hash}/similar": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Similar Samples
         * @description The catalog's samples whose spectral feature vector sits closest to this one's, nearest first.
         *
         *     Every neighbor is found by measuring this sample against the whole catalog at once, over the
         *     vectors held parsed for as long as the embedding behind them stands. Each arrives with what a
         *     glance shows, so a listing reads and plays without opening any of them.
         *
         *     Raises:
         *         HTTPException: 404 when this sample has no persisted spectral feature vector yet.
         */
        readonly get: operations["get_similar_samples_api_samples__sample_hash__similar_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/stats": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Stats
         * @description A snapshot of the catalog's overall size and composition.
         */
        readonly get: operations["get_stats_api_stats_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/cloud": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Cloud
         * @description Every sample's position in the library's 2D embedding space, as of the latest embedding run.
         *
         *     The answer is built once per revision of what it reads and served from memory after that: the
         *     coordinates' count and last write, the playback rates on file and the modules cataloged are
         *     what a pipeline moves, and three scalar queries say whether any has. A caller that accepts
         *     gzip receives the body compressed once at the best level rather than per request.
         */
        readonly get: operations["get_cloud_api_cloud_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/cloud/labels": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Cloud Labels
         * @description Every labeled sample's tags, for coloring the cloud by what a person decided.
         *
         *     These travel apart from the points on purpose: the labels are a few hundred rows against a
         *     hundred thousand points, and they change with every label a person writes while the points
         *     change only when the embedding is recomputed. A viewer joins the two by hash, so a labeled
         *     sample the current embedding holds no point for is simply not painted. Labels whose sample has
         *     left the catalog wait for relinking and stay off the cloud.
         */
        readonly get: operations["get_cloud_labels_api_cloud_labels_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/cloud/suggestions": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Cloud Suggestions
         * @description Every sample's first suggested tag from the newest scoring, for coloring the cloud by what a model hears.
         *
         *     These travel apart from the points the way the hand labels do: a scoring changes only when a
         *     pass writes a new one, so the newest scoring's id is the whole revision, and a viewer joins
         *     them to the points by hash. An empty answer says no scoring has been written.
         */
        readonly get: operations["get_cloud_suggestions_api_cloud_suggestions_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/cloud/suggestion-tags": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Cloud Suggestion Tags
         * @description Every tag the newest scoring suggests first for some sample, with how many and a lasting rank.
         *
         *     A specification counts toward its category the way a written label's does, so the legend can
         *     paint by category while the suggestions name what is under it. The rank is the tag's place in
         *     the vocabulary the scoring ranked, recorded with the scoring, a category taking the place of
         *     its first entry, so a tag keeps its color across the scorings that share a vocabulary; a tag
         *     the vocabulary leaves unnamed ranks after the vocabulary, by name.
         */
        readonly get: operations["get_cloud_suggestion_tags_api_cloud_suggestion_tags_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/cloud/modules": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Module Cloud
         * @description Every module's placeholder position in the library's 2D embedding space.
         *
         *     Placeholder until a spectral-distance-based per-module embedding replaces it -- see
         *     `samplecloud.placeholder_modules`.
         */
        readonly get: operations["get_module_cloud_api_cloud_modules_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/curation/annotations/{sample_hash}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post?: never;
        /**
         * Remove Annotation
         * @description Take back everything a person decided about one sample, whether or not the catalog still holds it.
         *
         *     An annotation whose sample has left the catalog for good, and that relinking cannot place, is
         *     removed through here.
         *
         *     Raises:
         *         HTTPException: 404 when no annotation is held for this hash.
         */
        readonly delete: operations["remove_annotation_api_curation_annotations__sample_hash__delete"];
        readonly options?: never;
        readonly head?: never;
        /**
         * Change Annotation
         * @description Change what a person decided about this sample, optionally across its near-duplicates.
         *
         *     Every reached sample keeps the decisions the request leaves out, so a star given to a group
         *     changes the members' ratings alone. A scope of ``equivalence_class`` reaches every sample the
         *     detector groups with this one, the same group the listing collapses under one row, and each
         *     member is written as its own row so the group boundary moving later leaves those decisions
         *     intact. A sample left recording nothing has its annotation removed, which is how a person takes
         *     a decision back.
         *
         *     The catalog is read through the read-only connection and only the curation schema is written,
         *     which keeps the one write this application performs to the schema it owns.
         *
         *     Raises:
         *         HTTPException: 404 when no sample is cataloged under this hash and none is annotated.
         */
        readonly patch: operations["change_annotation_api_curation_annotations__sample_hash__patch"];
        readonly trace?: never;
    };
    readonly "/api/curation/annotations/vocabulary": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Label Vocabulary
         * @description Every label already in use, most-used first, for offering a person their own wording back.
         */
        readonly get: operations["get_label_vocabulary_api_curation_annotations_vocabulary_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/curation/annotations/tags": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Label Tags
         * @description Every tag in use, read out of the labels as paths, most used first.
         *
         *     Where `get_label_vocabulary` offers whole wordings back to the person typing one, this reads the
         *     tags inside them -- ``HI-HAT: CLOSED, LO-FI`` names three -- for a viewer that colors or filters
         *     by what the labels say. The tree comes whole; a viewer takes the depth it wants.
         */
        readonly get: operations["get_label_tags_api_curation_annotations_tags_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/morph/audio": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Morph Audio
         * @description The audio at one point between two samples, rendered by the inference process and relayed as it came.
         *
         *     The catalog's rates for both ends travel with the point, so the process renders the pair in
         *     the one frame it is heard in and the file states that rate. The render's validator and its
         *     caching headers pass through untouched, and so does a caller's conditional request, so a
         *     browser that holds the render is answered with a 304 by the process that made it.
         *
         *     Raises:
         *         HTTPException: 503 when no inference process answers; the process's own 404 for a sample
         *             it has no object for, and 422 for a weight off the grid, are relayed with their detail.
         */
        readonly get: operations["get_morph_audio_api_morph_audio_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/morph/status": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Morph Status
         * @description Whether the inference process answers, and what it serves when it does.
         */
        readonly get: operations["get_morph_status_api_morph_status_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnnotationChangeRequest
         * @description The decisions one gesture changes about a sample, or about its whole group.
         *
         *     A decision left out of the request stays as the sample holds it; a decision sent as ``null``
         *     is cleared, and a favorite is cleared by sending ``false``. Values arrive as the JSON types they
         *     are, so a rating is a number and a favorite a boolean. An emptied label arrives as ``null``: text
         *     naming no tag is malformed rather than a way to clear one, which keeps a slip of the keyboard
         *     from silently discarding a decision.
         */
        readonly AnnotationChangeRequest: {
            readonly scope: components["schemas"]["AnnotationSource"];
            /** Label */
            readonly label?: string | null;
            /** Rating */
            readonly rating?: number | null;
            /**
             * Favorite
             * @default false
             */
            readonly favorite: boolean;
        };
        /**
         * AnnotationDecisions
         * @description The three things a person can decide about a sample.
         *
         *     The label says what the sample is, as free text: it records what a listener actually decided,
         *     ahead of any vocabulary being settled, so it stays unconstrained by `SampleCategory`'s fourteen
         *     guessed roles and wins wherever it exists. It is kept in upper case, which is the case it is
         *     shown in, so the vocabulary a person builds by habit collects one entry per wording. The rating and the favorite mark say what the
         *     listener thought of it, which is what turns browsing the library into a collection of a person's
         *     own.
         *
         *     Any one of them may stand alone, and all three may be empty: an empty set of decisions is how a
         *     person takes back everything they had said about a sample.
         */
        readonly AnnotationDecisions: {
            /** Label */
            readonly label: string | null;
            /** Rating */
            readonly rating: number | null;
            /** Favorite */
            readonly favorite: boolean;
        };
        /**
         * AnnotationSource
         * @description Whether an annotation was made for one sample or applied to a whole equivalence class.
         * @enum {string}
         */
        readonly AnnotationSource: "sample" | "equivalence_class";
        /**
         * AnnotationsWritten
         * @description What every reached sample now says, so a caller updates exactly the rows that changed.
         *
         *     ``skipped`` names the group members the change would have given a first decision to while the
         *     catalog holds nothing to anchor them to; they go on saying nothing.
         */
        readonly AnnotationsWritten: {
            /** Samples */
            readonly samples: readonly components["schemas"]["WrittenAnnotation"][];
            /** Skipped */
            readonly skipped: readonly string[];
        };
        /**
         * BitDepth
         * @description How many bits one stored frame of PCM occupies.
         *
         *     A :class:`~trackmod.core.samples.sample.Sample` holds float amplitudes whatever its depth. This is
         *     the width its frames are written at, and what a format's size model charges for them.
         *
         *     Example:
         *         >>> from trackmod import BitDepth
         *         >>> BitDepth.SIXTEEN.bytes_per_frame
         *         2
         *         >>> BitDepth.EIGHT.scale
         *         128.0
         * @enum {integer}
         */
        readonly BitDepth: 8 | 16;
        /**
         * ChannelLayout
         * @description How many interleaved channels one frame of a Sample's waveform carries.
         * @enum {integer}
         */
        readonly ChannelLayout: 1 | 2;
        /**
         * CloudLabel
         * @description What a person decided one sample is, as the tag paths they wrote, in the order they wrote them.
         *
         *     The order is kept because a point can show one color: the tag a person wrote first is the one
         *     they thought of first, so it is the one a viewer paints the point with.
         */
        readonly CloudLabel: {
            /** Sample Hash */
            readonly sample_hash: string;
            /** Paths */
            readonly paths: readonly (readonly string[])[];
        };
        /**
         * CloudSuggestion
         * @description What a listening model hears one sample as first: its closest suggested tag path, and how sure it was.
         *
         *     The first pick is the one a viewer paints the point with, the way the first written tag of a
         *     hand label is, and the one the legend counts; a sample's detail lists the picks behind it.
         */
        readonly CloudSuggestion: {
            /** Sample Hash */
            readonly sample_hash: string;
            /** Path */
            readonly path: readonly string[];
            /** Score */
            readonly score: number;
        };
        /** HTTPValidationError */
        readonly HTTPValidationError: {
            /** Detail */
            readonly detail?: readonly components["schemas"]["ValidationError"][];
        };
        /**
         * ITSampleProperties
         * @description The occurrence fields Impulse Tracker stores beside the shared ones.
         *
         *     ``global_volume`` is IT's own per-sample gain multiplier; FastTracker 2 has no equivalent
         *     slot, so it is not part of the shared base. ``filename`` and ``vibrato`` are this format's own
         *     DOS filename and sample-level auto-vibrato.
         */
        readonly ITSampleProperties: {
            /** Sample Hash */
            readonly sample_hash: string;
            readonly occurrence: components["schemas"]["SampleOccurrence"];
            /** Name */
            readonly name: string;
            /** Rate */
            readonly rate: number;
            /** Volume */
            readonly volume: number;
            /** Panning */
            readonly panning?: number | null;
            readonly loop?: components["schemas"]["Loop"] | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly tracker: "it";
            /** Global Volume */
            readonly global_volume: number;
            readonly sustain_loop?: components["schemas"]["Loop"] | null;
            /** Filename */
            readonly filename?: string | null;
            readonly vibrato?: components["schemas"]["Vibrato"] | null;
        };
        /**
         * LibraryStats
         * @description A snapshot of the catalog's overall size and composition.
         */
        readonly LibraryStats: {
            /** Module Count */
            readonly module_count: number;
            /** Sample Count */
            readonly sample_count: number;
            /** Sample Properties Count */
            readonly sample_properties_count: number;
            /** Modules By Tracker */
            readonly modules_by_tracker: readonly components["schemas"]["TrackerModuleCount"][];
            /** Relations By Type */
            readonly relations_by_type: readonly components["schemas"]["RelationTypeCount"][];
            /** Total Stored Bytes */
            readonly total_stored_bytes: number;
        };
        /**
         * Loop
         * @description A half-open frame range ``[begin, end)`` that playback repeats on reaching ``end``.
         *
         *     Args:
         *         begin: The first frame of the repeated region.
         *         end: One frame past the last, so the region spans ``end - begin`` frames.
         *         mode: Whether the region plays forward each time, or alternates direction.
         *
         *     Raises:
         *         ValidationError: when ``end`` is not above ``begin``. A loop spans at least one frame.
         *
         *     Example:
         *         >>> from trackmod import Loop
         *         >>> Loop(begin=8, end=64).frames
         *         56
         *         >>> Loop(begin=8, end=64).mode
         *         <LoopMode.FORWARD: 'forward'>
         */
        readonly Loop: {
            /** Begin */
            readonly begin: number;
            /** End */
            readonly end: number;
            /** @default forward */
            readonly mode: components["schemas"]["LoopMode"];
        };
        /**
         * LoopMode
         * @description How playback repeats a looped region.
         *
         *     ``FORWARD`` plays the region from ``begin`` each time round. ``PING_PONG`` alternates direction,
         *     playing it forward and then backward. Only Impulse Tracker and FastTracker 2 store ping-pong loops.
         * @enum {string}
         */
        readonly LoopMode: "forward" | "ping_pong";
        /**
         * MODSampleProperties
         * @description The occurrence fields Amiga ProTracker stores beside the shared ones.
         *
         *     ProTracker's own finetune byte only ever feeds into ``rate`` above -- TrackMod's MOD reader
         *     derives ``rate`` from it and keeps no separate raw copy, unlike FastTracker 2's ``tuning`` --
         *     and it stores no per-sample panning, sustain loop, filename, or vibrato of its own. This format
         *     carries nothing beyond the shared base; the subtype exists only so the discriminated union
         *     below can still tell a MOD occurrence apart from every other format's.
         */
        readonly MODSampleProperties: {
            /** Sample Hash */
            readonly sample_hash: string;
            readonly occurrence: components["schemas"]["SampleOccurrence"];
            /** Name */
            readonly name: string;
            /** Rate */
            readonly rate: number;
            /** Volume */
            readonly volume: number;
            /** Panning */
            readonly panning?: number | null;
            readonly loop?: components["schemas"]["Loop"] | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly tracker: "mod";
        };
        /**
         * Module
         * @description A tracker module file's identity and the shape of the song it stores.
         *
         *     ``hash`` content-addresses the exact file bytes; ``id`` is the library's own sequential handle
         *     for it, the pair mirroring how modsamplemaster.org identifies a module by both a hash and an
         *     id. ``filename`` is the module's own filename at ingestion time with no directory component --
         *     the local path it was ingested from is never recorded, only the name the file itself carried.
         */
        readonly Module: {
            /** Hash */
            readonly hash: string;
            /** Id */
            readonly id: number;
            /** Filename */
            readonly filename: string;
            readonly tracker: components["schemas"]["TrackerFormat"];
            /** Title */
            readonly title: string;
            /** Channel Count */
            readonly channel_count: number;
            /** Pattern Count */
            readonly pattern_count: number;
            /** Instrument Count */
            readonly instrument_count: number;
            /** Sample Count */
            readonly sample_count: number;
            /** File Size */
            readonly file_size: number;
            /**
             * Ingested At
             * Format: date-time
             */
            readonly ingested_at: string;
        };
        /**
         * ModuleCloudPoint
         * @description One module's place in the embedding: the coordinate alone, for the same reason a sample's point is.
         */
        readonly ModuleCloudPoint: {
            /** Module Hash */
            readonly module_hash: string;
            /** X */
            readonly x: number;
            /** Y */
            readonly y: number;
        };
        /**
         * ModuleDetail
         * @description A module together with every sample occurrence it declares.
         */
        readonly ModuleDetail: {
            /** Hash */
            readonly hash: string;
            /** Id */
            readonly id: number;
            /** Filename */
            readonly filename: string;
            readonly tracker: components["schemas"]["TrackerFormat"];
            /** Title */
            readonly title: string;
            /** Channel Count */
            readonly channel_count: number;
            /** Pattern Count */
            readonly pattern_count: number;
            /** Instrument Count */
            readonly instrument_count: number;
            /** Sample Count */
            readonly sample_count: number;
            /** File Size */
            readonly file_size: number;
            /**
             * Ingested At
             * Format: date-time
             */
            readonly ingested_at: string;
            /** Occurrences */
            readonly occurrences: readonly components["schemas"]["ModuleOccurrenceDetail"][];
        };
        /**
         * ModuleOccurrenceDetail
         * @description One sample occurrence a module declares, together with the Sample content it points at.
         */
        readonly ModuleOccurrenceDetail: {
            /** Properties */
            readonly properties: components["schemas"]["XMSampleProperties"] | components["schemas"]["ITSampleProperties"] | components["schemas"]["MODSampleProperties"] | components["schemas"]["S3MSampleProperties"];
            readonly sample: components["schemas"]["ModuleOccurrenceSample"];
        };
        /**
         * ModuleOccurrenceSample
         * @description The resolved Sample content one module occurrence points at, alongside its cached thumbnail.
         *
         *     ``size_bytes`` re-exposes ``Sample.stored_bytes`` under its own name, the same rename
         *     ``SampleSummary`` already uses: a Pydantic field cannot share a name with an inherited plain
         *     property without the property silently winning on attribute access.
         */
        readonly ModuleOccurrenceSample: {
            /** Hash */
            readonly hash: string;
            readonly depth: components["schemas"]["BitDepth"];
            readonly channels: components["schemas"]["ChannelLayout"];
            /** Frames */
            readonly frames: number;
            /** Size Bytes */
            readonly size_bytes: number;
            /** Thumbnail */
            readonly thumbnail: readonly components["schemas"]["WaveformPeak"][] | null;
        };
        /**
         * MorphAvailability
         * @description Whether morphs can be rendered right now, and by which model when they can.
         */
        readonly MorphAvailability: {
            /** Available */
            readonly available: boolean;
            readonly service: components["schemas"]["MorphServiceStatus"] | null;
        };
        /**
         * MorphServiceStatus
         * @description What an inference process serves: the model, the route it renders through, and the device it runs on.
         *
         *     The fingerprint names the exact model files loaded, so a render's cache identity changes with
         *     the model and with nothing else.
         */
        readonly MorphServiceStatus: {
            /** Model */
            readonly model: string;
            /** Codec */
            readonly codec: string;
            /** Canonicalizer */
            readonly canonicalizer: string;
            /** Latent Size */
            readonly latent_size: number;
            /** Vocoder */
            readonly vocoder: string;
            /** Restorer */
            readonly restorer: string | null;
            /** Device */
            readonly device: string;
            /** Fingerprint */
            readonly fingerprint: string;
            /** Weight Steps */
            readonly weight_steps: number;
        };
        /** Page[Module] */
        readonly Page_Module_: {
            /** Items */
            readonly items: readonly components["schemas"]["Module"][];
            /** Total */
            readonly total: number;
            /** Limit */
            readonly limit: number;
            /** Offset */
            readonly offset: number;
        };
        /** Page[SampleSummary] */
        readonly Page_SampleSummary_: {
            /** Items */
            readonly items: readonly components["schemas"]["SampleSummary"][];
            /** Total */
            readonly total: number;
            /** Limit */
            readonly limit: number;
            /** Offset */
            readonly offset: number;
        };
        /**
         * RelationReview
         * @description A curator's verdict on an automatically proposed SampleRelation, once one has been made.
         */
        readonly RelationReview: {
            /** Confirmed */
            readonly confirmed: boolean;
            /**
             * Reviewed At
             * Format: date-time
             */
            readonly reviewed_at: string;
            /** Reviewed By */
            readonly reviewed_by: string;
        };
        /**
         * RelationType
         * @description The kind of near-duplicate link two distinct Samples can be proposed to share.
         * @enum {string}
         */
        readonly RelationType: "bit_depth_variant" | "resampled_variant" | "amplification_variant";
        /**
         * RelationTypeCount
         * @description How many detected equivalence-class links belong to one relation type.
         */
        readonly RelationTypeCount: {
            readonly relation_type: components["schemas"]["RelationType"];
            /** Relation Count */
            readonly relation_count: number;
        };
        /**
         * S3MSampleProperties
         * @description The occurrence fields Scream Tracker 3 stores beside the shared ones.
         *
         *     ``filename`` is this format's own DOS filename, the one field Impulse Tracker's own
         *     ``ITSampleProperties.filename`` inherited from this format's lineage. Scream Tracker 3 stores
         *     no per-sample panning, sustain loop, or vibrato of its own.
         */
        readonly S3MSampleProperties: {
            /** Sample Hash */
            readonly sample_hash: string;
            readonly occurrence: components["schemas"]["SampleOccurrence"];
            /** Name */
            readonly name: string;
            /** Rate */
            readonly rate: number;
            /** Volume */
            readonly volume: number;
            /** Panning */
            readonly panning?: number | null;
            readonly loop?: components["schemas"]["Loop"] | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly tracker: "s3m";
            /** Filename */
            readonly filename?: string | null;
        };
        /**
         * SampleCategory
         * @description A coarse instrument-role classification for a sample, guessed from its occurrence names.
         * @enum {string}
         */
        readonly SampleCategory: "kick" | "snare" | "clap" | "hi_hat" | "cymbal" | "percussion" | "bass" | "lead" | "pad" | "pluck" | "vocal" | "fx" | "loop" | "uncategorized";
        /**
         * SampleCloudPoint
         * @description One sample's place in the embedding, with what a viewer needs to color and hear the point.
         *
         *     ``category`` is computed the same way `SampleSummary.category` is -- at read time, from the
         *     sample's own occurrence names together with the names of the instruments reaching it -- rather
         *     than stored alongside the coordinate itself. ``playback_rate_hz`` travels with the point so
         *     clicking one plays it at the speed the library really sounds it at; it is ``None`` for a sample
         *     the catalog knows no rate for.
         *
         *     This carries the coordinate's own fields rather than inheriting them, since a view of the whole
         *     catalog is a hundred thousand of these at once: when the run that placed them was computed says
         *     nothing about any one point, and a timestamp per point is several megabytes over the wire. The
         *     hand labels travel apart, through `/cloud/labels`, for the same reason.
         */
        readonly SampleCloudPoint: {
            /** Sample Hash */
            readonly sample_hash: string;
            /** X */
            readonly x: number;
            /** Y */
            readonly y: number;
            readonly category: components["schemas"]["SampleCategory"];
            /** Playback Rate Hz */
            readonly playback_rate_hz: number | null;
        };
        /**
         * SampleDetail
         * @description A sample together with every module occurrence that references it, and the rates it is heard at.
         *
         *     ``playback_rates`` holds every effective rate the library sounds this sample at, the most played
         *     first, so a listener can hear each of them; ``playback_rate_hz`` is the first of them.
         *     ``suggested_labels`` are what the newest scoring of the listening model hears the sample as,
         *     closest first, for a person to accept into the hand label or pass over.
         */
        readonly SampleDetail: {
            /** Hash */
            readonly hash: string;
            readonly depth: components["schemas"]["BitDepth"];
            readonly channels: components["schemas"]["ChannelLayout"];
            /** Frames */
            readonly frames: number;
            /** Display Name */
            readonly display_name: string;
            readonly category: components["schemas"]["SampleCategory"];
            /** Hand Label */
            readonly hand_label: string | null;
            /** Rating */
            readonly rating: number | null;
            /** Favorite */
            readonly favorite: boolean;
            /** Size Bytes */
            readonly size_bytes: number;
            /** Playback Rate Hz */
            readonly playback_rate_hz: number | null;
            /** Occurrences */
            readonly occurrences: readonly components["schemas"]["SampleOccurrenceDetail"][];
            /** Duration Seconds */
            readonly duration_seconds: number;
            /** Playback Rates */
            readonly playback_rates: readonly components["schemas"]["SamplePlaybackRate"][];
            /** Equivalence Member Count */
            readonly equivalence_member_count: number;
            /** Suggested Labels */
            readonly suggested_labels: readonly components["schemas"]["SuggestedLabel"][];
        };
        /**
         * SampleDistance
         * @description The spectral distance between two samples' persisted, standardized feature vectors.
         */
        readonly SampleDistance: {
            /** Sample Hash */
            readonly sample_hash: string;
            /** Other Hash */
            readonly other_hash: string;
            /** Distance */
            readonly distance: number;
        };
        /**
         * SampleOccurrence
         * @description Which one slot, in which one module, a SampleProperties row describes.
         *
         *     An instrument owns an ordered tuple of samples; ``sample_slot`` is a sample's position in
         *     that tuple -- the only handle XM or IT gives one occurrence, since neither assigns samples
         *     their own identifier independent of the instrument that owns them.
         */
        readonly SampleOccurrence: {
            /** Module Hash */
            readonly module_hash: string;
            /** Instrument Index */
            readonly instrument_index: number;
            /** Sample Slot */
            readonly sample_slot: number;
        };
        /**
         * SampleOccurrenceDetail
         * @description One module occurrence of a sample, together with the module it belongs to.
         */
        readonly SampleOccurrenceDetail: {
            /** Properties */
            readonly properties: components["schemas"]["XMSampleProperties"] | components["schemas"]["ITSampleProperties"] | components["schemas"]["MODSampleProperties"] | components["schemas"]["S3MSampleProperties"];
            readonly module: components["schemas"]["SampleOccurrenceModule"];
        };
        /**
         * SampleOccurrenceModule
         * @description The module context a sample occurrence belongs to, resolved for display alongside it.
         */
        readonly SampleOccurrenceModule: {
            /** Hash */
            readonly hash: string;
            /** Filename */
            readonly filename: string;
            /** Title */
            readonly title: string;
            readonly tracker: components["schemas"]["TrackerFormat"];
        };
        /**
         * SamplePlaybackRate
         * @description How often one sample is heard at one effective playback rate, across every module playing it.
         *
         *     This is the rate a waveform's frames are really read at: one number standing for an occurrence
         *     rate and a pressed key together. Read as a group, these say which speeds a sample is used at and
         *     how much each is leaned on, which is what lets a preview sound it the way the library does.
         */
        readonly SamplePlaybackRate: {
            /** Rate Hz */
            readonly rate_hz: number;
            /** Event Count */
            readonly event_count: number;
        };
        /**
         * SamplePreview
         * @description What a glance at a sample shows: its name, category and hand label, and the stored thumbnail of its waveform.
         *
         *     ``thumbnail`` is ``None`` for a sample the thumbnail pass has not reached, since a preview
         *     with nothing to draw is still a preview with a name.
         */
        readonly SamplePreview: {
            /** Display Name */
            readonly display_name: string;
            readonly category: components["schemas"]["SampleCategory"];
            /** Hand Label */
            readonly hand_label: string | null;
            /** Thumbnail */
            readonly thumbnail: readonly components["schemas"]["WaveformPeak"][] | null;
        };
        /**
         * SampleRelation
         * @description One automatically detected, optionally curator-reviewed link between two Samples.
         *
         *     ``subject_hash`` is always the lexicographically smaller of the two hashes, so the same pair,
         *     found by two different detection methods or in either order, always lands on the same identity
         *     for review purposes; ``method`` still lets independent detectors each record their own row for
         *     the same pair, so agreement between methods is itself visible corroborating evidence rather
         *     than being collapsed away.
         */
        readonly SampleRelation: {
            /** Id */
            readonly id: number;
            /** Subject Hash */
            readonly subject_hash: string;
            /** Reference Hash */
            readonly reference_hash: string;
            readonly relation_type: components["schemas"]["RelationType"];
            /** Method */
            readonly method: string;
            /** Confidence */
            readonly confidence: number;
            /** Evidence */
            readonly evidence: {
                readonly [key: string]: number;
            };
            /**
             * Detected At
             * Format: date-time
             */
            readonly detected_at: string;
            readonly review?: components["schemas"]["RelationReview"] | null;
        };
        /**
         * SampleSort
         * @description The orders a samples listing can be walked in.
         * @enum {string}
         */
        readonly SampleSort: "occurrences" | "rating";
        /**
         * SampleSummary
         * @description One row of a paginated, occurrence-ranked samples listing.
         *
         *     Ranks samples by identity -- one row per exact content hash -- rather than by equivalence
         *     class; grouping near-duplicate variants into one row is a distinct future ranking mode, not a
         *     hidden variant of this one. ``thumbnail`` is ``None`` for a sample whose cached waveform preview
         *     has not been computed yet. ``equivalence_class_hash`` identifies the group of near-duplicate
         *     variants this sample belongs to, resolved from the whole catalog's relation graph, and is
         *     ``None`` for a sample with no detected relation. ``equivalence_member_count`` is that class's
         *     total size (1 for a sample with no class), independent of how many of its members are present on
         *     this page.
         */
        readonly SampleSummary: {
            /** Hash */
            readonly hash: string;
            readonly depth: components["schemas"]["BitDepth"];
            readonly channels: components["schemas"]["ChannelLayout"];
            /** Frames */
            readonly frames: number;
            /** Display Name */
            readonly display_name: string;
            readonly category: components["schemas"]["SampleCategory"];
            /** Hand Label */
            readonly hand_label: string | null;
            /** Rating */
            readonly rating: number | null;
            /** Favorite */
            readonly favorite: boolean;
            /** Size Bytes */
            readonly size_bytes: number;
            /** Playback Rate Hz */
            readonly playback_rate_hz: number | null;
            /** Occurrence Count */
            readonly occurrence_count: number;
            /** Thumbnail */
            readonly thumbnail: readonly components["schemas"]["WaveformPeak"][] | null;
            /** Equivalence Class Hash */
            readonly equivalence_class_hash: string | null;
            /** Equivalence Member Count */
            readonly equivalence_member_count: number;
        };
        /**
         * SimilarSample
         * @description One neighbor in a sample's spectral-distance nearest-neighbor listing: a glance at it, how far it sits, and the rate to hear it at.
         *
         *     ``playback_rate_hz`` travels with the neighbor so a listener hears it at the speed the library
         *     really plays it; it is ``None`` for a sample the catalog knows no rate for.
         */
        readonly SimilarSample: {
            /** Display Name */
            readonly display_name: string;
            readonly category: components["schemas"]["SampleCategory"];
            /** Hand Label */
            readonly hand_label: string | null;
            /** Thumbnail */
            readonly thumbnail: readonly components["schemas"]["WaveformPeak"][] | null;
            /** Hash */
            readonly hash: string;
            /** Distance */
            readonly distance: number;
            /** Playback Rate Hz */
            readonly playback_rate_hz: number | null;
        };
        /**
         * SuggestedLabel
         * @description One tag a listening model suggests for a sample, in the hand-label grammar, and how sure it was.
         */
        readonly SuggestedLabel: {
            /** Label */
            readonly label: string;
            /** Score */
            readonly score: number;
        };
        /**
         * TagSummary
         * @description One tag a person has used: its path, how many samples carry it, and a rank that stays with it.
         *
         *     The count includes every sample labeled with a specification below the tag. The rank follows
         *     the order tags were first used in and stays with its tag for good, which is what a viewer hangs
         *     a lasting color on.
         */
        readonly TagSummary: {
            /** Path */
            readonly path: readonly string[];
            /** Sample Count */
            readonly sample_count: number;
            /** Rank */
            readonly rank: number;
        };
        /**
         * TrackerFormat
         * @description Which tracker format a module or a sample occurrence belongs to.
         * @enum {string}
         */
        readonly TrackerFormat: "xm" | "it" | "mod" | "s3m";
        /**
         * TrackerModuleCount
         * @description How many cataloged modules belong to one tracker format.
         */
        readonly TrackerModuleCount: {
            readonly tracker: components["schemas"]["TrackerFormat"];
            /** Module Count */
            readonly module_count: number;
        };
        /**
         * Tuning
         * @description How far a stored sample is transposed from the key that triggers it.
         *
         *     FastTracker 2 stores no playback rate. A sample sounds at the pitch of the key it is played on,
         *     shifted by ``relative_note`` whole semitones and trimmed by ``finetune`` in units of one
         *     :data:`~trackmod.xm.spec.tuning.FINETUNE_UNITS`-th of a semitone, so a rate is expressed as a
         *     transposition rather than stored outright.
         */
        readonly Tuning: {
            /** Relative Note */
            readonly relative_note: number;
            /** Finetune */
            readonly finetune: number;
        };
        /** ValidationError */
        readonly ValidationError: {
            /** Location */
            readonly loc: readonly (string | number)[];
            /** Message */
            readonly msg: string;
            /** Error Type */
            readonly type: string;
            /** Input */
            readonly input?: unknown;
            /** Context */
            readonly ctx?: Record<string, never>;
        };
        /**
         * Vibrato
         * @description The auto-vibrato an Impulse Tracker sample header carries in its own right.
         *
         *     Newer instrument-format modules commonly leave this at its silent default and drive vibrato
         *     from the owning instrument instead, but the sample header field exists regardless of which a
         *     given module actually relies on, so it is captured here rather than assumed unused.
         */
        readonly Vibrato: {
            /** Speed */
            readonly speed: number;
            /** Depth */
            readonly depth: number;
            /** Rate */
            readonly rate: number;
            /** Waveform */
            readonly waveform: number;
        };
        /**
         * WaveformPeak
         * @description One bucket's amplitude envelope in a compact waveform preview.
         */
        readonly WaveformPeak: {
            /** Minimum */
            readonly minimum: number;
            /** Maximum */
            readonly maximum: number;
        };
        /**
         * WrittenAnnotation
         * @description What one reached sample says once a write has landed, ``null`` for a sample saying nothing.
         */
        readonly WrittenAnnotation: {
            /** Sample Hash */
            readonly sample_hash: string;
            readonly annotation: components["schemas"]["AnnotationDecisions"] | null;
        };
        /**
         * XMSampleProperties
         * @description The occurrence fields FastTracker 2 stores beside the shared ones.
         *
         *     FastTracker 2 keeps no separate per-sample gain, no sustain loop, and no auto-vibrato on the
         *     sample itself, so ``tuning`` is the only field this format adds: the raw transposition its own
         *     header stores, which ``rate`` above was already derived from by TrackMod's XM reader.
         */
        readonly XMSampleProperties: {
            /** Sample Hash */
            readonly sample_hash: string;
            readonly occurrence: components["schemas"]["SampleOccurrence"];
            /** Name */
            readonly name: string;
            /** Rate */
            readonly rate: number;
            /** Volume */
            readonly volume: number;
            /** Panning */
            readonly panning?: number | null;
            readonly loop?: components["schemas"]["Loop"] | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly tracker: "xm";
            readonly tuning: components["schemas"]["Tuning"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly list_modules_api_modules_get: {
        readonly parameters: {
            readonly query?: {
                readonly limit?: number;
                readonly offset?: number;
                readonly tracker?: components["schemas"]["TrackerFormat"] | null;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Page_Module_"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_module_api_modules__module_hash__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly module_hash: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ModuleDetail"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly list_samples_api_samples_get: {
        readonly parameters: {
            readonly query?: {
                readonly limit?: number;
                readonly offset?: number;
                readonly group_by_equivalence?: boolean;
                readonly favorites_only?: boolean;
                readonly minimum_rating?: number | null;
                readonly sort?: components["schemas"]["SampleSort"];
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Page_SampleSummary_"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_sample_api_samples__sample_hash__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly sample_hash: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SampleDetail"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_sample_audio_api_samples__sample_hash__audio_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly sample_hash: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_sample_preview_api_samples__sample_hash__preview_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly sample_hash: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SamplePreview"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_sample_relations_api_samples__sample_hash__relations_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly sample_hash: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["SampleRelation"][];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_sample_distance_api_samples__sample_hash__distance__other_hash__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly sample_hash: string;
                readonly other_hash: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SampleDistance"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_similar_samples_api_samples__sample_hash__similar_get: {
        readonly parameters: {
            readonly query?: {
                readonly limit?: number;
            };
            readonly header?: never;
            readonly path: {
                readonly sample_hash: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["SimilarSample"][];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_stats_api_stats_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["LibraryStats"];
                };
            };
        };
    };
    readonly get_cloud_api_cloud_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["SampleCloudPoint"][];
                };
            };
        };
    };
    readonly get_cloud_labels_api_cloud_labels_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["CloudLabel"][];
                };
            };
        };
    };
    readonly get_cloud_suggestions_api_cloud_suggestions_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["CloudSuggestion"][];
                };
            };
        };
    };
    readonly get_cloud_suggestion_tags_api_cloud_suggestion_tags_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["TagSummary"][];
                };
            };
        };
    };
    readonly get_module_cloud_api_cloud_modules_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["ModuleCloudPoint"][];
                };
            };
        };
    };
    readonly remove_annotation_api_curation_annotations__sample_hash__delete: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly sample_hash: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly change_annotation_api_curation_annotations__sample_hash__patch: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly sample_hash: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["AnnotationChangeRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["AnnotationsWritten"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_label_vocabulary_api_curation_annotations_vocabulary_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly string[];
                };
            };
        };
    };
    readonly get_label_tags_api_curation_annotations_tags_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["TagSummary"][];
                };
            };
        };
    };
    readonly get_morph_audio_api_morph_audio_get: {
        readonly parameters: {
            readonly query: {
                readonly first: string;
                readonly second: string;
                readonly weight: number;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_morph_status_api_morph_status_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["MorphAvailability"];
                };
            };
        };
    };
}
