/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/api/modules": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * List Modules
         * @description A page of cataloged modules, optionally filtered by tracker format.
         */
        readonly get: operations["list_modules_api_modules_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/modules/{module_hash}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Module
         * @description One module's own fields plus every sample occurrence it declares.
         *
         *     Raises:
         *         HTTPException: 404 when no module is cataloged under this hash.
         */
        readonly get: operations["get_module_api_modules__module_hash__get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/samples": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * List Samples
         * @description A page of the catalog's samples, narrowed and ordered by what a person has decided.
         *
         *     ``favorites_only`` and ``minimum_rating`` reach the whole catalog rather than one page, so a
         *     collection scattered across a hundred thousand samples still browses as a collection.
         *     ``group_by_equivalence`` collapses same-page rows sharing an equivalence class afterwards, which
         *     is why the total counts rows rather than groups.
         */
        readonly get: operations["list_samples_api_samples_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/samples/{sample_hash}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Sample
         * @description One sample's own fields plus every module occurrence that references it.
         *
         *     ``equivalence_member_count`` travels with the sample so a caller labeling it knows how many
         *     near-duplicates the same choice would reach.
         *
         *     Raises:
         *         HTTPException: 404 when no sample is cataloged under this hash.
         */
        readonly get: operations["get_sample_api_samples__sample_hash__get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/samples/{sample_hash}/audio": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Sample Audio
         * @description The sample's own canonical audio, as stored in the content-addressable store.
         *
         *     Raises:
         *         HTTPException: 404 when no sample is cataloged under this hash.
         */
        readonly get: operations["get_sample_audio_api_samples__sample_hash__audio_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/samples/{sample_hash}/waveform": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Sample Waveform
         * @description A compact amplitude-envelope preview of the sample's own waveform.
         *
         *     Raises:
         *         HTTPException: 404 when no sample is cataloged under this hash.
         */
        readonly get: operations["get_sample_waveform_api_samples__sample_hash__waveform_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/samples/{sample_hash}/relations": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Sample Relations
         * @description Every equivalence-class link this sample participates in, on either side of the pair.
         *
         *     Raises:
         *         HTTPException: 404 when no sample is cataloged under this hash.
         */
        readonly get: operations["get_sample_relations_api_samples__sample_hash__relations_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/samples/{sample_hash}/distance/{other_hash}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Sample Distance
         * @description The Euclidean distance between two samples' persisted, standardized spectral feature vectors.
         *
         *     Raises:
         *         HTTPException: 404 when either sample has no persisted spectral feature vector yet -- not
         *             yet embedded, or embedded before this metric existed.
         */
        readonly get: operations["get_sample_distance_api_samples__sample_hash__distance__other_hash__get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/samples/{sample_hash}/similar": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Similar Samples
         * @description The catalog's samples whose spectral feature vector sits closest to this one's, nearest first.
         *
         *     Raises:
         *         HTTPException: 404 when this sample has no persisted spectral feature vector yet.
         */
        readonly get: operations["get_similar_samples_api_samples__sample_hash__similar_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/stats": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Stats
         * @description A snapshot of the catalog's overall size and composition.
         */
        readonly get: operations["get_stats_api_stats_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/cloud": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Cloud
         * @description Every sample's position in the library's 2D embedding space, as of the latest embedding run.
         */
        readonly get: operations["get_cloud_api_cloud_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/cloud/modules": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Module Cloud
         * @description Every module's placeholder position in the library's 2D embedding space.
         *
         *     Placeholder until a spectral-distance-based per-module embedding replaces it -- see
         *     `samplecloud.placeholder_modules`.
         */
        readonly get: operations["get_module_cloud_api_cloud_modules_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/curation/annotations/{sample_hash}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        /**
         * Set Annotation
         * @description Record what a person decided about this sample, optionally across its near-duplicates.
         *
         *     The whole state arrives at once and replaces whatever the sample said before. A state recording
         *     nothing removes the annotation, which is how a person takes a decision back.
         *
         *     A scope of ``equivalence_class`` reaches every sample the detector groups with this one, which
         *     is the same group the listing collapses under one row, and each member is written as its own row
         *     so the group boundary moving later leaves those decisions intact. A sample with no detected
         *     relation forms a group of one, so both scopes behave identically for it. A member the catalog
         *     holds no occurrence for has nowhere to anchor, so its annotation is removed rather than left
         *     saying something the group no longer says.
         *
         *     The catalog is read through the read-only connection and only the annotation is written, which
         *     keeps the one write this application performs to the schema it owns.
         *
         *     Raises:
         *         HTTPException: 404 when no sample is cataloged under this hash.
         */
        readonly put: operations["set_annotation_api_curation_annotations__sample_hash__put"];
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/curation/annotations/vocabulary": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Label Vocabulary
         * @description Every label already in use, most-used first, for offering a person their own wording back.
         */
        readonly get: operations["get_label_vocabulary_api_curation_annotations_vocabulary_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnnotationDecisions
         * @description The three things a person can decide about a sample.
         *
         *     The label says what the sample is, as free text: it records what a listener actually decided,
         *     ahead of any vocabulary being settled, so it stays unconstrained by `SampleCategory`'s fourteen
         *     guessed roles and wins wherever it exists. The rating and the favorite mark say what the
         *     listener thought of it, which is what turns browsing the library into a collection of a person's
         *     own.
         *
         *     Any one of them may stand alone, and all three may be empty: an empty set of decisions is how a
         *     person takes back everything they had said about a sample.
         */
        readonly AnnotationDecisions: {
            /** Label */
            readonly label: string | null;
            /** Rating */
            readonly rating: number | null;
            /** Favorite */
            readonly favorite: boolean;
        };
        /**
         * AnnotationRequest
         * @description The whole state a person wants a sample, or its whole group, to carry from here on.
         *
         *     Every decision is sent on every write, so what a person left empty is what the sample ends up
         *     saying nothing about. An emptied label arrives as ``null``: blank text is malformed rather than
         *     a way to clear one, which keeps a slip of the keyboard from silently discarding a decision.
         */
        readonly AnnotationRequest: {
            /** Label */
            readonly label: string | null;
            /** Rating */
            readonly rating: number | null;
            /** Favorite */
            readonly favorite: boolean;
            readonly scope: components["schemas"]["AnnotationSource"];
        };
        /**
         * AnnotationSource
         * @description Whether an annotation was made for one sample or applied to a whole equivalence class.
         * @enum {string}
         */
        readonly AnnotationSource: "sample" | "equivalence_class";
        /**
         * AnnotationWritten
         * @description What every reached sample now says, so a caller updates exactly the rows that changed.
         */
        readonly AnnotationWritten: {
            readonly annotation: components["schemas"]["AnnotationDecisions"] | null;
            /** Sample Hashes */
            readonly sample_hashes: readonly string[];
        };
        /**
         * BitDepth
         * @description How many bits one stored frame of PCM occupies.
         *
         *     A :class:`~trackmod.core.samples.sample.Sample` holds float amplitudes whatever its depth. This is
         *     the width its frames are written at, and what a format's size model charges for them.
         *
         *     Example:
         *         >>> from trackmod import BitDepth
         *         >>> BitDepth.SIXTEEN.bytes_per_frame
         *         2
         *         >>> BitDepth.EIGHT.scale
         *         128.0
         * @enum {integer}
         */
        readonly BitDepth: 8 | 16;
        /**
         * ChannelLayout
         * @description How many interleaved channels one frame of a Sample's waveform carries.
         * @enum {integer}
         */
        readonly ChannelLayout: 1 | 2;
        /** HTTPValidationError */
        readonly HTTPValidationError: {
            /** Detail */
            readonly detail?: readonly components["schemas"]["ValidationError"][];
        };
        /**
         * ITSampleProperties
         * @description The occurrence fields Impulse Tracker stores beside the shared ones.
         *
         *     ``global_volume`` is IT's own per-sample gain multiplier; FastTracker 2 has no equivalent
         *     slot, so it is not part of the shared base. ``filename`` and ``vibrato`` are this format's own
         *     DOS filename and sample-level auto-vibrato.
         */
        readonly ITSampleProperties: {
            /** Sample Hash */
            readonly sample_hash: string;
            readonly occurrence: components["schemas"]["SampleOccurrence"];
            /** Name */
            readonly name: string;
            /** Rate */
            readonly rate: number;
            /** Volume */
            readonly volume: number;
            /** Panning */
            readonly panning?: number | null;
            readonly loop?: components["schemas"]["Loop"] | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly tracker: "it";
            /** Global Volume */
            readonly global_volume: number;
            readonly sustain_loop?: components["schemas"]["Loop"] | null;
            /** Filename */
            readonly filename?: string | null;
            readonly vibrato?: components["schemas"]["Vibrato"] | null;
        };
        /**
         * LibraryStats
         * @description A snapshot of the catalog's overall size and composition.
         */
        readonly LibraryStats: {
            /** Module Count */
            readonly module_count: number;
            /** Sample Count */
            readonly sample_count: number;
            /** Sample Properties Count */
            readonly sample_properties_count: number;
            /** Modules By Tracker */
            readonly modules_by_tracker: readonly components["schemas"]["TrackerModuleCount"][];
            /** Relations By Type */
            readonly relations_by_type: readonly components["schemas"]["RelationTypeCount"][];
            /** Total Stored Bytes */
            readonly total_stored_bytes: number;
        };
        /**
         * Loop
         * @description A half-open frame range ``[begin, end)`` that playback repeats on reaching ``end``.
         *
         *     Args:
         *         begin: The first frame of the repeated region.
         *         end: One frame past the last, so the region spans ``end - begin`` frames.
         *         mode: Whether the region plays forward each time, or alternates direction.
         *
         *     Raises:
         *         ValidationError: when ``end`` is not above ``begin``. A loop spans at least one frame.
         *
         *     Example:
         *         >>> from trackmod import Loop
         *         >>> Loop(begin=8, end=64).frames
         *         56
         *         >>> Loop(begin=8, end=64).mode
         *         <LoopMode.FORWARD: 'forward'>
         */
        readonly Loop: {
            /** Begin */
            readonly begin: number;
            /** End */
            readonly end: number;
            /** @default forward */
            readonly mode: components["schemas"]["LoopMode"];
        };
        /**
         * LoopMode
         * @description How playback repeats a looped region.
         *
         *     ``FORWARD`` plays the region from ``begin`` each time round. ``PING_PONG`` alternates direction,
         *     playing it forward and then backward. Only Impulse Tracker and FastTracker 2 store ping-pong loops.
         * @enum {string}
         */
        readonly LoopMode: "forward" | "ping_pong";
        /**
         * MODSampleProperties
         * @description The occurrence fields Amiga ProTracker stores beside the shared ones.
         *
         *     ProTracker's own finetune byte only ever feeds into ``rate`` above -- TrackMod's MOD reader
         *     derives ``rate`` from it and keeps no separate raw copy, unlike FastTracker 2's ``tuning`` --
         *     and it stores no per-sample panning, sustain loop, filename, or vibrato of its own. This format
         *     carries nothing beyond the shared base; the subtype exists only so the discriminated union
         *     below can still tell a MOD occurrence apart from every other format's.
         */
        readonly MODSampleProperties: {
            /** Sample Hash */
            readonly sample_hash: string;
            readonly occurrence: components["schemas"]["SampleOccurrence"];
            /** Name */
            readonly name: string;
            /** Rate */
            readonly rate: number;
            /** Volume */
            readonly volume: number;
            /** Panning */
            readonly panning?: number | null;
            readonly loop?: components["schemas"]["Loop"] | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly tracker: "mod";
        };
        /**
         * Module
         * @description A tracker module file's identity and the shape of the song it stores.
         *
         *     ``hash`` content-addresses the exact file bytes; ``id`` is the library's own sequential handle
         *     for it, the pair mirroring how modsamplemaster.org identifies a module by both a hash and an
         *     id. ``filename`` is the module's own filename at ingestion time with no directory component --
         *     the local path it was ingested from is never recorded, only the name the file itself carried.
         */
        readonly Module: {
            /** Hash */
            readonly hash: string;
            /** Id */
            readonly id: number;
            /** Filename */
            readonly filename: string;
            readonly tracker: components["schemas"]["TrackerFormat"];
            /** Title */
            readonly title: string;
            /** Channel Count */
            readonly channel_count: number;
            /** Pattern Count */
            readonly pattern_count: number;
            /** Instrument Count */
            readonly instrument_count: number;
            /** Sample Count */
            readonly sample_count: number;
            /** File Size */
            readonly file_size: number;
            /**
             * Ingested At
             * Format: date-time
             */
            readonly ingested_at: string;
        };
        /**
         * ModuleCloudCoordinate
         * @description Where one Module sits in the library's 2D embedding space, as of one embedding run.
         *
         *     Today's positions come from `samplecloud.placeholder_modules`, seeded from a module's own hash
         *     rather than a genuine similarity fit -- standing in until a spectral-distance metric makes a
         *     real per-module embedding possible. A later run's coordinate for a given hash entirely replaces
         *     an earlier one, mirroring SampleCloudCoordinate's own replacement semantics.
         */
        readonly ModuleCloudCoordinate: {
            /** Module Hash */
            readonly module_hash: string;
            /** X */
            readonly x: number;
            /** Y */
            readonly y: number;
            /**
             * Computed At
             * Format: date-time
             */
            readonly computed_at: string;
        };
        /**
         * ModuleDetail
         * @description A module together with every sample occurrence it declares.
         */
        readonly ModuleDetail: {
            /** Hash */
            readonly hash: string;
            /** Id */
            readonly id: number;
            /** Filename */
            readonly filename: string;
            readonly tracker: components["schemas"]["TrackerFormat"];
            /** Title */
            readonly title: string;
            /** Channel Count */
            readonly channel_count: number;
            /** Pattern Count */
            readonly pattern_count: number;
            /** Instrument Count */
            readonly instrument_count: number;
            /** Sample Count */
            readonly sample_count: number;
            /** File Size */
            readonly file_size: number;
            /**
             * Ingested At
             * Format: date-time
             */
            readonly ingested_at: string;
            /** Occurrences */
            readonly occurrences: readonly components["schemas"]["ModuleOccurrenceDetail"][];
        };
        /**
         * ModuleOccurrenceDetail
         * @description One sample occurrence a module declares, together with the Sample content it points at.
         */
        readonly ModuleOccurrenceDetail: {
            /** Properties */
            readonly properties: components["schemas"]["XMSampleProperties"] | components["schemas"]["ITSampleProperties"] | components["schemas"]["MODSampleProperties"] | components["schemas"]["S3MSampleProperties"];
            readonly sample: components["schemas"]["ModuleOccurrenceSample"];
        };
        /**
         * ModuleOccurrenceSample
         * @description The resolved Sample content one module occurrence points at, alongside its cached thumbnail.
         *
         *     ``size_bytes`` re-exposes ``Sample.stored_bytes`` under its own name, the same rename
         *     ``SampleSummary`` already uses: a Pydantic field cannot share a name with an inherited plain
         *     property without the property silently winning on attribute access.
         */
        readonly ModuleOccurrenceSample: {
            /** Hash */
            readonly hash: string;
            readonly depth: components["schemas"]["BitDepth"];
            readonly channels: components["schemas"]["ChannelLayout"];
            /** Frames */
            readonly frames: number;
            /** Size Bytes */
            readonly size_bytes: number;
            /** Thumbnail */
            readonly thumbnail: readonly components["schemas"]["WaveformPeak"][] | null;
        };
        /**
         * Note
         * @description A playable key, counted in semitones above C-0.
         *
         *     Trackers number their keyboards from C-0, and the octave a tracker prints is one above the octave the
         *     same pitch carries in MIDI: tracker C-5 is MIDI note 72. The stored number is the tracker numbering,
         *     which Impulse Tracker writes directly and FastTracker 2 writes offset by one.
         */
        readonly Note: number;
        /** Page[Module] */
        readonly Page_Module_: {
            /** Items */
            readonly items: readonly components["schemas"]["Module"][];
            /** Total */
            readonly total: number;
            /** Limit */
            readonly limit: number;
            /** Offset */
            readonly offset: number;
        };
        /** Page[SampleSummary] */
        readonly Page_SampleSummary_: {
            /** Items */
            readonly items: readonly components["schemas"]["SampleSummary"][];
            /** Total */
            readonly total: number;
            /** Limit */
            readonly limit: number;
            /** Offset */
            readonly offset: number;
        };
        /**
         * RelationReview
         * @description A curator's verdict on an automatically proposed SampleRelation, once one has been made.
         */
        readonly RelationReview: {
            /** Confirmed */
            readonly confirmed: boolean;
            /**
             * Reviewed At
             * Format: date-time
             */
            readonly reviewed_at: string;
            /** Reviewed By */
            readonly reviewed_by: string;
        };
        /**
         * RelationType
         * @description The kind of near-duplicate link two distinct Samples can be proposed to share.
         * @enum {string}
         */
        readonly RelationType: "bit_depth_variant" | "resampled_variant" | "amplification_variant";
        /**
         * RelationTypeCount
         * @description How many detected equivalence-class links belong to one relation type.
         */
        readonly RelationTypeCount: {
            readonly relation_type: components["schemas"]["RelationType"];
            /** Relation Count */
            readonly relation_count: number;
        };
        /**
         * S3MSampleProperties
         * @description The occurrence fields Scream Tracker 3 stores beside the shared ones.
         *
         *     ``filename`` is this format's own DOS filename, the one field Impulse Tracker's own
         *     ``ITSampleProperties.filename`` inherited from this format's lineage. Scream Tracker 3 stores
         *     no per-sample panning, sustain loop, or vibrato of its own.
         */
        readonly S3MSampleProperties: {
            /** Sample Hash */
            readonly sample_hash: string;
            readonly occurrence: components["schemas"]["SampleOccurrence"];
            /** Name */
            readonly name: string;
            /** Rate */
            readonly rate: number;
            /** Volume */
            readonly volume: number;
            /** Panning */
            readonly panning?: number | null;
            readonly loop?: components["schemas"]["Loop"] | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly tracker: "s3m";
            /** Filename */
            readonly filename?: string | null;
        };
        /**
         * SampleCategory
         * @description A coarse instrument-role classification for a sample, guessed from its occurrence names.
         * @enum {string}
         */
        readonly SampleCategory: "kick" | "snare" | "clap" | "hi_hat" | "cymbal" | "percussion" | "bass" | "lead" | "pad" | "pluck" | "vocal" | "fx" | "loop" | "uncategorized";
        /**
         * SampleCloudPoint
         * @description A SampleCloudCoordinate together with what a viewer needs to color and hear the point.
         *
         *     ``category`` is computed the same way `SampleSummary.category` is -- at read time, from the
         *     sample's own occurrence names together with the names of the instruments reaching it -- rather
         *     than stored alongside the coordinate itself. ``dominant_rate_hz`` travels with the point so
         *     clicking one plays it at a real tracker rate; it is ``None`` for a sample with no occurrences.
         *     ``hand_label`` carries what a person decided this sample is, for a viewer inspecting a point;
         *     the cloud keeps coloring by ``category``, whose fourteen roles hold a fixed hue each.
         */
        readonly SampleCloudPoint: {
            /** Sample Hash */
            readonly sample_hash: string;
            /** X */
            readonly x: number;
            /** Y */
            readonly y: number;
            /**
             * Computed At
             * Format: date-time
             */
            readonly computed_at: string;
            readonly category: components["schemas"]["SampleCategory"];
            /** Hand Label */
            readonly hand_label: string | null;
            /** Dominant Rate Hz */
            readonly dominant_rate_hz: number | null;
        };
        /**
         * SampleDetail
         * @description A sample together with every module occurrence that references it, and the notes it is played at.
         */
        readonly SampleDetail: {
            /** Hash */
            readonly hash: string;
            readonly depth: components["schemas"]["BitDepth"];
            readonly channels: components["schemas"]["ChannelLayout"];
            /** Frames */
            readonly frames: number;
            /** Display Name */
            readonly display_name: string;
            readonly category: components["schemas"]["SampleCategory"];
            /** Hand Label */
            readonly hand_label: string | null;
            /** Rating */
            readonly rating: number | null;
            /** Favorite */
            readonly favorite: boolean;
            /** Size Bytes */
            readonly size_bytes: number;
            /** Dominant Rate Hz */
            readonly dominant_rate_hz: number | null;
            /** Occurrences */
            readonly occurrences: readonly components["schemas"]["SampleOccurrenceDetail"][];
            /** Duration Seconds */
            readonly duration_seconds: number;
            /** Notes Played */
            readonly notes_played: readonly components["schemas"]["SampleNotePlayed"][];
            /** Equivalence Member Count */
            readonly equivalence_member_count: number;
        };
        /**
         * SampleDistance
         * @description The spectral distance between two samples' persisted, standardized feature vectors.
         */
        readonly SampleDistance: {
            /** Sample Hash */
            readonly sample_hash: string;
            /** Other Hash */
            readonly other_hash: string;
            /** Distance */
            readonly distance: number;
        };
        /**
         * SampleNotePlayed
         * @description One note a sample is heard at, with how often the library plays it there.
         *
         *     ``sounding_rate_hz`` reads the note against the sample's dominant occurrence rate, which is the
         *     rate a preview would otherwise play at, so a caller can sound the sample as the library really
         *     uses it rather than at its bare reference rate.
         */
        readonly SampleNotePlayed: {
            /** Sounded Note */
            readonly sounded_note: number;
            /** Note Name */
            readonly note_name: string;
            /** Event Count */
            readonly event_count: number;
            /** Sounding Rate Hz */
            readonly sounding_rate_hz: number | null;
        };
        /**
         * SampleOccurrence
         * @description Which one slot, in which one module, a SampleProperties row describes.
         *
         *     An instrument owns an ordered tuple of samples; ``sample_slot`` is a sample's position in
         *     that tuple -- the only handle XM or IT gives one occurrence, since neither assigns samples
         *     their own identifier independent of the instrument that owns them.
         */
        readonly SampleOccurrence: {
            /** Module Hash */
            readonly module_hash: string;
            /** Instrument Index */
            readonly instrument_index: number;
            /** Sample Slot */
            readonly sample_slot: number;
        };
        /**
         * SampleOccurrenceDetail
         * @description One module occurrence of a sample, together with the module it belongs to.
         */
        readonly SampleOccurrenceDetail: {
            /** Properties */
            readonly properties: components["schemas"]["XMSampleProperties"] | components["schemas"]["ITSampleProperties"] | components["schemas"]["MODSampleProperties"] | components["schemas"]["S3MSampleProperties"];
            readonly module: components["schemas"]["SampleOccurrenceModule"];
        };
        /**
         * SampleOccurrenceModule
         * @description The module context a sample occurrence belongs to, resolved for display alongside it.
         */
        readonly SampleOccurrenceModule: {
            /** Hash */
            readonly hash: string;
            /** Filename */
            readonly filename: string;
            /** Title */
            readonly title: string;
            readonly tracker: components["schemas"]["TrackerFormat"];
        };
        /**
         * SampleRelation
         * @description One automatically detected, optionally curator-reviewed link between two Samples.
         *
         *     ``subject_hash`` is always the lexicographically smaller of the two hashes, so the same pair,
         *     found by two different detection methods or in either order, always lands on the same identity
         *     for review purposes; ``method`` still lets independent detectors each record their own row for
         *     the same pair, so agreement between methods is itself visible corroborating evidence rather
         *     than being collapsed away.
         */
        readonly SampleRelation: {
            /** Id */
            readonly id: number;
            /** Subject Hash */
            readonly subject_hash: string;
            /** Reference Hash */
            readonly reference_hash: string;
            readonly relation_type: components["schemas"]["RelationType"];
            /** Method */
            readonly method: string;
            /** Confidence */
            readonly confidence: number;
            /** Evidence */
            readonly evidence: {
                readonly [key: string]: number;
            };
            /**
             * Detected At
             * Format: date-time
             */
            readonly detected_at: string;
            readonly review?: components["schemas"]["RelationReview"] | null;
        };
        /**
         * SampleSort
         * @description The orders a samples listing can be walked in.
         * @enum {string}
         */
        readonly SampleSort: "occurrences" | "rating";
        /**
         * SampleSummary
         * @description One row of a paginated, occurrence-ranked samples listing.
         *
         *     Ranks samples by identity -- one row per exact content hash -- rather than by equivalence
         *     class; grouping near-duplicate variants into one row is a distinct future ranking mode, not a
         *     hidden variant of this one. ``thumbnail`` is ``None`` for a sample whose cached waveform preview
         *     has not been computed yet. ``equivalence_class_hash`` identifies the group of near-duplicate
         *     variants this sample belongs to, resolved from the whole catalog's relation graph, and is
         *     ``None`` for a sample with no detected relation. ``equivalence_member_count`` is that class's
         *     total size (1 for a sample with no class), independent of how many of its members are present on
         *     this page. ``dominant_note`` is the note the library plays this sample at most often, which with
         *     ``dominant_rate_hz`` gives the pitch a preview should sound at; it is ``None`` for a sample whose
         *     modules have not had their patterns read, and for one no pattern plays.
         */
        readonly SampleSummary: {
            /** Hash */
            readonly hash: string;
            readonly depth: components["schemas"]["BitDepth"];
            readonly channels: components["schemas"]["ChannelLayout"];
            /** Frames */
            readonly frames: number;
            /** Display Name */
            readonly display_name: string;
            readonly category: components["schemas"]["SampleCategory"];
            /** Hand Label */
            readonly hand_label: string | null;
            /** Rating */
            readonly rating: number | null;
            /** Favorite */
            readonly favorite: boolean;
            /** Size Bytes */
            readonly size_bytes: number;
            /** Dominant Rate Hz */
            readonly dominant_rate_hz: number | null;
            /** Occurrence Count */
            readonly occurrence_count: number;
            /** Thumbnail */
            readonly thumbnail: readonly components["schemas"]["WaveformPeak"][] | null;
            readonly dominant_note: components["schemas"]["Note"] | null;
            /** Equivalence Class Hash */
            readonly equivalence_class_hash: string | null;
            /** Equivalence Member Count */
            readonly equivalence_member_count: number;
        };
        /**
         * SimilarSample
         * @description One neighbor in a sample's spectral-distance nearest-neighbor listing.
         *
         *     ``dominant_rate_hz`` travels with the neighbor so a listener hears it at a real tracker rate
         *     rather than at the stored file's own header rate; it is ``None`` for a sample with no occurrences.
         */
        readonly SimilarSample: {
            /** Hash */
            readonly hash: string;
            /** Distance */
            readonly distance: number;
            /** Dominant Rate Hz */
            readonly dominant_rate_hz: number | null;
        };
        /**
         * TrackerFormat
         * @description Which tracker format a module or a sample occurrence belongs to.
         * @enum {string}
         */
        readonly TrackerFormat: "xm" | "it" | "mod" | "s3m";
        /**
         * TrackerModuleCount
         * @description How many cataloged modules belong to one tracker format.
         */
        readonly TrackerModuleCount: {
            readonly tracker: components["schemas"]["TrackerFormat"];
            /** Module Count */
            readonly module_count: number;
        };
        /**
         * Tuning
         * @description How far a stored sample is transposed from the key that triggers it.
         *
         *     FastTracker 2 stores no playback rate. A sample sounds at the pitch of the key it is played on,
         *     shifted by ``relative_note`` whole semitones and trimmed by ``finetune`` in units of one
         *     :data:`~trackmod.xm.spec.tuning.FINETUNE_UNITS`-th of a semitone, so a rate is expressed as a
         *     transposition rather than stored outright.
         */
        readonly Tuning: {
            /** Relative Note */
            readonly relative_note: number;
            /** Finetune */
            readonly finetune: number;
        };
        /** ValidationError */
        readonly ValidationError: {
            /** Location */
            readonly loc: readonly (string | number)[];
            /** Message */
            readonly msg: string;
            /** Error Type */
            readonly type: string;
            /** Input */
            readonly input?: unknown;
            /** Context */
            readonly ctx?: Record<string, never>;
        };
        /**
         * Vibrato
         * @description The auto-vibrato an Impulse Tracker sample header carries in its own right.
         *
         *     Newer instrument-format modules commonly leave this at its silent default and drive vibrato
         *     from the owning instrument instead, but the sample header field exists regardless of which a
         *     given module actually relies on, so it is captured here rather than assumed unused.
         */
        readonly Vibrato: {
            /** Speed */
            readonly speed: number;
            /** Depth */
            readonly depth: number;
            /** Rate */
            readonly rate: number;
            /** Waveform */
            readonly waveform: number;
        };
        /**
         * WaveformPeak
         * @description One bucket's amplitude envelope in a compact waveform preview.
         */
        readonly WaveformPeak: {
            /** Minimum */
            readonly minimum: number;
            /** Maximum */
            readonly maximum: number;
        };
        /**
         * XMSampleProperties
         * @description The occurrence fields FastTracker 2 stores beside the shared ones.
         *
         *     FastTracker 2 keeps no separate per-sample gain, no sustain loop, and no auto-vibrato on the
         *     sample itself, so ``tuning`` is the only field this format adds: the raw transposition its own
         *     header stores, which ``rate`` above was already derived from by TrackMod's XM reader.
         */
        readonly XMSampleProperties: {
            /** Sample Hash */
            readonly sample_hash: string;
            readonly occurrence: components["schemas"]["SampleOccurrence"];
            /** Name */
            readonly name: string;
            /** Rate */
            readonly rate: number;
            /** Volume */
            readonly volume: number;
            /** Panning */
            readonly panning?: number | null;
            readonly loop?: components["schemas"]["Loop"] | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly tracker: "xm";
            readonly tuning: components["schemas"]["Tuning"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly list_modules_api_modules_get: {
        readonly parameters: {
            readonly query?: {
                readonly limit?: number;
                readonly offset?: number;
                readonly tracker?: components["schemas"]["TrackerFormat"] | null;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Page_Module_"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_module_api_modules__module_hash__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly module_hash: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ModuleDetail"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly list_samples_api_samples_get: {
        readonly parameters: {
            readonly query?: {
                readonly limit?: number;
                readonly offset?: number;
                readonly group_by_equivalence?: boolean;
                readonly favorites_only?: boolean;
                readonly minimum_rating?: number | null;
                readonly sort?: components["schemas"]["SampleSort"];
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Page_SampleSummary_"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_sample_api_samples__sample_hash__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly sample_hash: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SampleDetail"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_sample_audio_api_samples__sample_hash__audio_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly sample_hash: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": unknown;
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_sample_waveform_api_samples__sample_hash__waveform_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly sample_hash: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["WaveformPeak"][];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_sample_relations_api_samples__sample_hash__relations_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly sample_hash: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["SampleRelation"][];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_sample_distance_api_samples__sample_hash__distance__other_hash__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly sample_hash: string;
                readonly other_hash: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SampleDistance"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_similar_samples_api_samples__sample_hash__similar_get: {
        readonly parameters: {
            readonly query?: {
                readonly limit?: number;
            };
            readonly header?: never;
            readonly path: {
                readonly sample_hash: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["SimilarSample"][];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_stats_api_stats_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["LibraryStats"];
                };
            };
        };
    };
    readonly get_cloud_api_cloud_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["SampleCloudPoint"][];
                };
            };
        };
    };
    readonly get_module_cloud_api_cloud_modules_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["ModuleCloudCoordinate"][];
                };
            };
        };
    };
    readonly set_annotation_api_curation_annotations__sample_hash__put: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly sample_hash: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["AnnotationRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["AnnotationWritten"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_label_vocabulary_api_curation_annotations_vocabulary_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly string[];
                };
            };
        };
    };
}
