/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/api/setup/state": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Read State */
        readonly get: operations["read_state_api_setup_state_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/setup/sources": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        /**
         * Choose Sources
         * @description Write the library's folders into the config file and open the library under them.
         *
         *     Raises:
         *         HTTPException: 422 when the folders fail validation, naming what to change.
         */
        readonly put: operations["choose_sources_api_setup_sources_put"];
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/setup/builds": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Start Build
         * @description Start building the library, and answer with the state the build shows in.
         *
         *     Raises:
         *         HTTPException: 409 while the library is closed or another build runs.
         */
        readonly post: operations["start_build_api_setup_builds_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/setup/builds/cancel": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Cancel Build */
        readonly post: operations["cancel_build_api_setup_builds_cancel_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/setup/places": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Read Places */
        readonly get: operations["read_places_api_setup_places_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/setup/folders": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Read Folder
         * @description One folder's contents for the folder browser.
         *
         *     Raises:
         *         HTTPException: 404 when the path names no folder the system lets this application list.
         */
        readonly get: operations["read_folder_api_setup_folders_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/setup/quit": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Quit Application */
        readonly post: operations["quit_application_api_setup_quit_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BuildRequest */
        readonly BuildRequest: {
            readonly target: components["schemas"]["BuildTarget"];
        };
        /**
         * BuildTarget
         * @description What a person asks the application to build: the catalog of their folders, or the whole library with its cloud.
         * @enum {string}
         */
        readonly BuildTarget: "catalog" | "all";
        /** Folder */
        readonly Folder: {
            /** Name */
            readonly name: string;
            /** Path */
            readonly path: string;
        };
        /**
         * FolderListing
         * @description One folder as the folder browser shows it: the folders inside it, and how many modules and audio files it holds itself.
         *
         *     The counts cover the folder's own files, which is what a person needs to recognize a collection
         *     while the listing stays quick on a large one.
         */
        readonly FolderListing: {
            /** Path */
            readonly path: string;
            /** Parent */
            readonly parent: string | null;
            /** Folders */
            readonly folders: readonly components["schemas"]["Folder"][];
            /** Module Files */
            readonly module_files: number;
            /** Audio Files */
            readonly audio_files: number;
        };
        /** HTTPValidationError */
        readonly HTTPValidationError: {
            /** Detail */
            readonly detail?: readonly components["schemas"]["ValidationError"][];
        };
        /**
         * JobStatus
         * @enum {string}
         */
        readonly JobStatus: "running" | "completed" | "failed" | "canceled";
        /**
         * JobView
         * @description One build as the application shows it: its steps in order, the running step's progress, and why it failed.
         */
        readonly JobView: {
            readonly target: components["schemas"]["BuildTarget"];
            readonly status: components["schemas"]["JobStatus"];
            /**
             * Started At
             * Format: date-time
             */
            readonly started_at: string;
            /** Ended At */
            readonly ended_at: string | null;
            /** Steps */
            readonly steps: readonly components["schemas"]["StepView"][];
            /** Problem */
            readonly problem: string | null;
            /** Log Tail */
            readonly log_tail: readonly string[];
        };
        /**
         * LibrarySources
         * @description What a person chooses for their library: where it lives, and the folders it reads modules and samples from.
         *
         *     The application writes these into the config file for a person who never opens it, and reads
         *     them back to show what the library holds.
         */
        readonly LibrarySources: {
            /**
             * Library Root
             * Format: path
             */
            readonly library_root: string;
            /** Module Source Directory */
            readonly module_source_directory: string | null;
            /** Sample Directories */
            readonly sample_directories: readonly string[];
            /** Sample Exclusions */
            readonly sample_exclusions: readonly string[];
        };
        /**
         * LibraryStatus
         * @description Where the application stands with its library: waiting for a person's choices, opening it, open, or stuck.
         * @enum {string}
         */
        readonly LibraryStatus: "unconfigured" | "starting" | "ready" | "failed";
        /**
         * Place
         * @description A folder the folder browser offers as a starting point: a person's own folders, and every drive.
         */
        readonly Place: {
            /** Name */
            readonly name: string;
            /** Path */
            readonly path: string;
        };
        /**
         * ProgressReport
         * @description How far one pass has come, as the program watching it reads it: what it counts, how many are done, of how many.
         */
        readonly ProgressReport: {
            /** Label */
            readonly label: string;
            /** Done */
            readonly done: number;
            /** Total */
            readonly total: number;
            /**
             * Updated At
             * Format: date-time
             */
            readonly updated_at: string;
        };
        /**
         * SetupState
         * @description What the setup pages show: the library's status, the sources chosen for it, and what went wrong if anything did.
         */
        readonly SetupState: {
            readonly status: components["schemas"]["LibraryStatus"];
            /** Config Path */
            readonly config_path: string;
            readonly sources: components["schemas"]["LibrarySources"] | null;
            /** Suggested Library Root */
            readonly suggested_library_root: string;
            /** Manages Database */
            readonly manages_database: boolean | null;
            /** Problem */
            readonly problem: string | null;
            readonly build: components["schemas"]["JobView"] | null;
        };
        /**
         * StepState
         * @description Where one step of a build stands, as a person reads it off the build's checklist.
         * @enum {string}
         */
        readonly StepState: "waiting" | "up to date" | "running" | "done" | "failed" | "skipped";
        /** StepView */
        readonly StepView: {
            /** Name */
            readonly name: string;
            readonly state: components["schemas"]["StepState"];
            readonly progress: components["schemas"]["ProgressReport"] | null;
        };
        /** ValidationError */
        readonly ValidationError: {
            /** Location */
            readonly loc: readonly (string | number)[];
            /** Message */
            readonly msg: string;
            /** Error Type */
            readonly type: string;
            /** Input */
            readonly input?: unknown;
            /** Context */
            readonly ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly read_state_api_setup_state_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SetupState"];
                };
            };
        };
    };
    readonly choose_sources_api_setup_sources_put: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["LibrarySources"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SetupState"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly start_build_api_setup_builds_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["BuildRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 202: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SetupState"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly cancel_build_api_setup_builds_cancel_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SetupState"];
                };
            };
        };
    };
    readonly read_places_api_setup_places_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["Place"][];
                };
            };
        };
    };
    readonly read_folder_api_setup_folders_get: {
        readonly parameters: {
            readonly query: {
                readonly path: string;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["FolderListing"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly quit_application_api_setup_quit_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 202: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": unknown;
                };
            };
        };
    };
}
